# Generated by Django 5.2.6 on 2025-09-16 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('thumbnail', models.URLField(verbose_name='')),
                ('category', models.CharField(choices=[('ball', 'Bola'), ('shoes', 'Sepatu Bola'), ('jersey', 'Jersey'), ('gloves', 'Sarung Tangan'), ('accessories', 'Aksesoris')], default='bola', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
